language: node_js
node_js:
- "10"
cache:
  yarn: true
  directories:
  - node_modules
addons:
  sonarcloud:
    organization: xyo-network
install:
- yarn install
script:
- yarn build
- sonar-scanner
deploy:
  provider: npm
  skip_cleanup: true
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
deploy:
  provider: npm
  skip_cleanup: true
  tag: alpha
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: develop